os: osx
language: go
install:
- brew install hugo
before_script:
- cd ..
- git clone --recursive https://github.com/navn-r/notes
- cd notes
- git submodule update --recursive
script:
- hugo --minify
deploy:
  strategy: git
  provider: pages
  repo: navn-r/notes
  target_dir: '/Users/travis/gopath/src/github.com/navn-r/notes'
  skip_cleanup: true
  token: $GITHUB_TOKEN 
  target_branch: master
  keep_history: true
  on:
    branch: master
