dist: xenial
language: go
addons:
  snaps:
    - hugo
before_script:
- cd ..
- git clone -b master --recursive https://github.com/navn-r/notes ./master
- cd master ; git submodule update --recursive --remote
- rm -rf docs ; rm -rf content
- cd .. ; mv ./notes ./master/content ; cd master
script:
- hugo --minify
after_success:
- rm -rf content
deploy:
  strategy: git
  provider: pages
  local_dir: '/home/travis/gopath/src/github.com/navn-r/master/'
  skip_cleanup: true
  token: $GITHUB_TOKEN 
  target_branch: master
  keep_history: true
  on:
    branch: src
